FROM node:18-alpine AS builder

# Define build arguments with default values
ARG PUBLIC_REST_API_PROTOCOL=http
ARG PUBLIC_REST_API_HOSTNAME=64.227.121.226
ARG PUBLIC_REST_API_PORT=5123
ARG PUBLIC_SOCKET_API_PROTOCOL=ws
ARG PUBLIC_SOCKET_API_HOSTNAME=64.227.121.226
ARG PUBLIC_SOCKET_API_PORT=5123

# Set environment variables from build arguments
ENV PUBLIC_REST_API_PROTOCOL=${PUBLIC_REST_API_PROTOCOL}
ENV PUBLIC_REST_API_HOSTNAME=${PUBLIC_REST_API_HOSTNAME}
ENV PUBLIC_REST_API_PORT=${PUBLIC_REST_API_PORT}
ENV PUBLIC_SOCKET_API_PROTOCOL=${PUBLIC_SOCKET_API_PROTOCOL}
ENV PUBLIC_SOCKET_API_HOSTNAME=${PUBLIC_SOCKET_API_HOSTNAME}
ENV PUBLIC_SOCKET_API_PORT=${PUBLIC_SOCKET_API_PORT}

WORKDIR /app
COPY package*.json .
RUN npm ci
COPY . .
RUN npm run build
RUN npm prune --production

FROM node:18-alpine
WORKDIR /app
COPY --from=builder /app/build build/
COPY --from=builder /app/node_modules node_modules/
COPY package.json .
EXPOSE 3000
CMD [ "node", "build" ]